export const ru = {
  app: {
    title: 'Симулятор уязвимости',
    subtitle: 'Исследовательская платформа банковского приложения и цифрового кошелька',
    disclaimer:
      'Демонстрационные данные. Реальные переводы и интеграции не выполняются.',
    fatalErrorTitle: 'Приложение не удалось загрузить',
    fatalErrorDescription:
      'Перезагрузите страницу. Если ошибка повторяется, проверьте, что запущены npm run dev и npm run dev:registry.',
    fatalErrorReload: 'Перезагрузить',
  },
  nav: {
    groupStudy: 'Исследование',
    groupContent: 'Контент',
    simulations: 'Симуляции',
    analytics: 'Аналитика',
    scenarioContent: 'Сценарии',
    riskRules: 'Правила риска',
    adminLogin: 'Вход для редакторов',
    adminLogout: 'Выйти',
    simulationsHelp: 'Запуск симуляций и сбор данных о поведении',
    analyticsHelp: 'Сводка сессий, фильтры и детализация',
    scenarioContentHelp: 'Подготовка, review и публикация сценариев',
    riskRulesHelp: 'Настройка правил автоматической оценки риска',
    ariaLabel: 'Основная навигация',
  },
  actions: {
    backToSimulations: 'К симуляциям',
    backToAnalytics: 'К аналитике',
    backToScenarioList: 'К списку сценариев',
    backToRuleList: 'К списку правил',
  },
  researcher: {
    sectionOverviewTitle: 'Разделы платформы',
    sectionOpenLink: 'Перейти',
    sections: {
      simulations: {
        title: 'Симуляции',
        description: 'Запуск сценариев от имени профиля пользователя. Здесь начинается исследование.',
      },
      analytics: {
        title: 'Аналитика',
        description: 'KPI, фильтры и детализация по завершённым сессиям. Только просмотр результатов.',
      },
      scenarioContent: {
        title: 'Сценарии (контент)',
        description: 'Редактирование конфигураций сценариев, review и публикация для симуляций.',
      },
      riskRules: {
        title: 'Правила риска',
        description: 'Настройка правил scoring и review перед публикацией в runtime.',
      },
    },
    hubHint:
      'Запустите симуляцию от имени выбранного профиля. После завершения сессия попадёт в аналитику и просмотр событий.',
    hubEmptyTitle: 'Сценарии не найдены',
    hubEmptySteps: [
      'Сбросьте фильтры симулятора и уровня риска.',
      'Убедитесь, что выбран профиль, подходящий для сценария.',
      'Если нужен новый сценарий — создайте его в разделе «Сценарии» (контент).',
    ],
    analyticsHint:
      'Только просмотр: сводка завершённых сессий, фильтры, детализация и экспорт для анализа.',
    analyticsEmptyTitle: 'Пока нет данных для аналитики',
    analyticsEmptySteps: [
      'Откройте «Симуляции» и завершите хотя бы один сценарий.',
      'Вернитесь в «Аналитику» — сессия появится в KPI и таблице.',
      'Откройте «Просмотр» в строке сессии или «Объяснение» для высокого риска.',
    ],
    analyticsFilteredEmptyTitle: 'Нет сессий по фильтрам',
    analyticsFilteredEmptyMessage: 'Измените фильтры или сбросьте диапазон дат.',
    analyticsFilteredEmptySteps: [
      'Сбросьте фильтры сценария, профиля и исхода.',
      'Очистите поля дат «с» и «по».',
      'Вернитесь к полной выборке на главной странице аналитики.',
    ],
    analyticsExportTitle: 'Экспорт данных',
    analyticsExportDescription:
      'Выгрузка текущей выборки или сводных метрик для внешнего анализа.',
    authoringHint:
      'Подготовка и review конфигураций сценариев. Опубликованные версии доступны в симуляциях.',
    authoringEmptyTitle: 'Каталог сценариев пуст',
    authoringEmptySteps: [
      'Создайте черновик банковского или кошелькового сценария.',
      'Или импортируйте готовую JSON-конфигурацию.',
      'После публикации сценарий появится в «Симуляциях».',
    ],
    rulesHint:
      'Настройка правил автоматической оценки риска. Опубликованные правила участвуют в scoring сессий.',
    rulesEmptyTitle: 'Каталог правил пуст',
    rulesEmptyMessage: 'Создайте правило или клонируйте встроенное в черновик.',
    authoringEmptyMessage: 'Создайте черновик или импортируйте JSON-конфигурацию.',
    rulesEmptySteps: [
      'Создайте новое правило scoring.',
      'Или клонируйте встроенное правило в черновик для правок.',
      'После публикации правило участвует в оценке новых сессий.',
    ],
    replayHint:
      'Разбор одной сессии: метаданные, сводка поведения, оценка риска и хронология событий.',
    replayNotFoundTitle: 'Сессия не найдена',
    replayNotFoundSteps: [
      'Проверьте ссылку или откройте сессию из таблицы в аналитике.',
      'Если сессия только что завершена — обновите страницу аналитики.',
      'Запустите новую симуляцию, если данных ещё нет.',
    ],
    loginHint:
      'Вход нужен для редактирования контента, review и публикации. Симуляции и аналитика доступны без входа.',
    reviewStatesLegend: 'Статусы review: черновик → на review → опубликовано.',
    drilldownEmptyTitle: 'Нет данных для детализации',
    drilldownEmptySteps: [
      'Вернитесь в аналитику и расширьте фильтры выборки.',
      'Убедитесь, что в выборке есть сессии с нужным сценарием, флагом или правилом.',
      'Сбросьте фильтры дат, если период слишком узкий.',
    ],
    explainNotFoundSteps: [
      'Проверьте ссылку или откройте сессию из таблицы в аналитике.',
      'Убедитесь, что сессия завершена — активные сессии не попадают в объяснение.',
      'Вернитесь к аналитике и выберите сессию из списка высокого риска.',
    ],
    explainUnavailableSteps: [
      'Откройте «Просмотр» сессии — там доступны метаданные и события.',
      'Если сессия без riskReport, объяснение scoring может быть недоступно.',
      'Запустите новую симуляцию, если данных ещё нет.',
    ],
    compareInsufficientSteps: [
      'Выберите другой режим сравнения (сценарий, симулятор или период).',
      'Расширьте фильтры — для сравнения нужны сессии в обеих группах.',
      'Сбросьте фильтры дат, если период слишком узкий.',
    ],
    explainHint:
      'Пошаговое объяснение оценки риска: флаги, вклад правил и причины высокого score.',
    workflow: {
      pathTitle: 'Рекомендуемый путь исследования',
      pathDescription:
        'Симуляция → аналитика → разбор (explain/replay) → выводы и следующие действия.',
      dismissIntro: 'Скрыть подсказку',
      startHint: 'Начните с запуска любого сценария — данные появятся в аналитике после завершения.',
      steps: {
        simulate: 'Симуляция',
        analytics: 'Аналитика',
        investigate: 'Разбор',
        conclude: 'Выводы',
      },
      nextStepsTitle: 'Что делать дальше',
      nextStepsDefault: 'Выберите следующий шаг исследования.',
      postSimTitle: 'Симуляция завершена',
      postSimMessage: 'Сессия сохранена. Перейдите к аналитике или разберите поведение в replay.',
      nextStepsAnalytics: 'Изучите KPI и таблицу сессий. Сравните сценарии или запустите новую симуляцию.',
      nextStepsAnalyticsHighRisk: (count: number) =>
        `В выборке ${count} сессий с высоким риском — начните с блока «Высокий риск» ниже.`,
      nextStepsExplain: 'Посмотрите хронологию событий в replay или вернитесь к аналитике.',
      nextStepsReplay: 'При необходимости откройте explain для высокого риска или вернитесь к аналитике.',
      ctaOpenAnalytics: 'Открыть аналитику',
      ctaOpenReplay: 'Просмотр сессии',
      ctaOpenExplain: 'Объяснение риска',
      ctaReviewHighRisk: 'К высокому риску',
      ctaCompare: 'Сравнить сценарии',
      ctaNewSimulation: 'Новая симуляция',
      ctaOpenScenario: 'К сценарию',
      ctaOpenRule: 'К правилу',
      quickFiltersTitle: 'Быстрые представления',
      quickFiltersHint: 'Типовые выборки для triage — фильтры применяются к текущей аналитике.',
      presets: {
        highRisk: 'Высокий риск',
        abandonedRisky: 'Брошенные рискованные',
        warningDismiss: 'Игнор предупреждения',
        walletSuspicious: 'Подозрительный кошелёк',
      },
      investigationTitle: 'Разбор сессии',
      investigationHint: 'Быстрые действия и triage-метка для вашего исследования.',
      markers: {
        pending: 'Не разобрано',
        reviewed: 'Разобрано',
        flagged: 'На внимание',
      },
      noteLabel: 'Заметка (локально)',
      notePlaceholder: 'Краткая заметка для себя — не синхронизируется между устройствами.',
    },
  },
  screens: {
    scenarios: 'Симуляции',
    banking: 'Банковское приложение',
    wallet: 'Цифровой кошелёк',
    dashboard: 'Аналитика сессий',
  },
  buttons: {
    startScenario: 'Начать сценарий',
    back: 'Назад',
    backToScenarios: 'К симуляциям',
    continue: 'Продолжить',
    cancel: 'Отменить',
    cancelOperation: 'Отменить операцию',
    confirm: 'Подтвердить',
    confirmTransfer: 'Подтвердить перевод',
    goToReview: 'Перейти к проверке',
    addRecipient: 'Добавить получателя',
    finishScenario: 'Завершить сценарий',
  },
  hub: {
    filtersTitle: 'Фильтры',
    filterSimulator: 'Тип симулятора',
    filterRisk: 'Уровень риска',
    filterAll: 'Все',
    simulatorBanking: 'Банк',
    simulatorWallet: 'Кошелёк',
    profileLabel: 'Профиль пользователя',
    profilePlaceholder: 'Выберите профиль',
    scenariosCount: 'сценариев',
    warningsOn: 'Предупреждения включены',
    warningsOff: 'Предупреждения выключены',
    stepsLabel: 'Шаги',
    expectedFlagsLabel: 'Ожидаемые флаги',
    noScenarios: 'Нет сценариев по выбранным фильтрам.',
    resetFilters: 'Сбросить фильтры',
    selectProfileHint: 'Выберите профиль, чтобы начать сценарий',
    profileNotSupported: 'Профиль не подходит для этого сценария. Выберите другой профиль.',
  },
  riskLevel: {
    low: 'Низкий',
    medium: 'Средний',
    high: 'Высокий',
  },
  risk: {
    panelTitle: 'Оценка риска последней сессии',
    scoreLabel: 'Risk score',
    levelLabel: 'Уровень риска',
    flagsLabel: 'Сработавшие правила',
    noFlags: 'Правила риска не сработали.',
    noSession: 'Завершите сценарий, чтобы увидеть оценку риска.',
    rules: {
      ignored_warning: {
        label: 'Игнор предупреждения',
        description: 'Пользователь увидел предупреждение, но продолжил действие',
      },
      warning_seen_then_cancelled: {
        label: 'Остановка после предупреждения',
        description: 'После предупреждения пользователь отменил операцию',
      },
      fast_confirmation_in_risky_flow: {
        label: 'Быстрое подтверждение',
        description: 'Подтверждение выполнено слишком быстро в рискованном сценарии',
      },
      new_recipient_in_risky_scenario: {
        label: 'Новый получатель',
        description: 'В рискованном сценарии добавлен новый получатель',
      },
      repeated_field_edits: {
        label: 'Повторное редактирование полей',
        description: 'Реквизиты менялись несколько раз',
      },
      multiple_back_navigation_loops: {
        label: 'Циклы навигации',
        description: 'Много переходов назад между экранами',
      },
      recovery_phrase_entered: {
        label: 'Секретная фраза',
        description: 'Пользователь ввёл фразу восстановления',
      },
      malicious_approval_signed: {
        label: 'Опасное разрешение',
        description: 'Подписано потенциально вредоносное разрешение',
      },
      signature_rejected_after_warning: {
        label: 'Отказ после предупреждения',
        description: 'Подпись отклонена после просмотра предупреждения',
      },
      user_stopped_after_warning: {
        label: 'Остановка на warning',
        description: 'Пользователь остановился после предупреждения',
      },
    },
  },
  banking: {
    screens: {
      home: 'Главный экран',
      accounts: 'Счета',
      transfer: 'Перевод',
      newRecipient: 'Получатель',
      review: 'Проверка данных',
      warning: 'Предупреждение',
      confirm: 'Подтверждение',
      result: 'Результат операции',
    },
    fields: {
      recipientAccount: 'Номер счёта получателя',
      recipientName: 'Имя получателя',
      recipientBank: 'Банк получателя',
      amount: 'Сумма перевода',
      comment: 'Комментарий',
      confirmationCode: 'Код подтверждения',
    },
    home: {
      greeting: 'Добро пожаловать',
      mainAccount: 'Основной счёт',
      availableBalance: 'Доступно',
      quickTransfer: 'Перевести',
      viewAccounts: 'Мои счета',
    },
    accounts: {
      title: 'Ваши счета',
      openTransfer: 'Перевод между счетами',
    },
    transfer: {
      title: 'Новый перевод',
      hint: 'Выберите способ перевода',
      toNewRecipient: 'Перевод новому получателю',
    },
    newRecipient: {
      title: 'Новый получатель',
      phoneCallBanner:
        'Если вы выполняете действия по инструкции во время звонка, остановитесь и перепроверьте операцию.',
    },
    review: {
      title: 'Проверка данных',
      recipient: 'Получатель',
      amount: 'Сумма',
      comment: 'Комментарий',
      noComment: '—',
    },
    warnings: {
      safeAccount:
        'Внимание: если вас просят срочно перевести деньги на «безопасный счёт», это может быть мошенничество.',
      noShareCodes:
        'Не сообщайте никому коды подтверждения, PIN-код и данные карты.',
      newRecipientWarning:
        'Вы добавляете нового получателя и выполняете перевод сразу после предупреждения.',
      verifyDetails:
        'Проверьте имя получателя и реквизиты перед подтверждением.',
      phoneInstruction:
        'Если вы выполняете действия по инструкции во время звонка, остановитесь и перепроверьте операцию.',
    },
    confirm: {
      title: 'Подтверждение перевода',
      hint: 'Введите код подтверждения из демонстрационного сообщения',
      demoCodeHint: 'Для симуляции подойдёт любой код из 4 цифр',
    },
    results: {
      confirmed: 'Операция подтверждена',
      cancelled: 'Операция отменена',
      scenarioDone: 'Сценарий завершён',
    },
  },
  wallet: {
    screens: {
      walletHome: 'Главный экран кошелька',
      assets: 'Активы',
      connectApp: 'Подключение приложения',
      signatureRequest: 'Запрос подписи',
      approvalWarning: 'Предупреждение',
      recovery: 'Восстановление',
      result: 'Результат операции',
    },
    fields: {
      serviceName: 'Название сервиса',
      walletAddress: 'Адрес кошелька',
      recoveryPhrase: 'Секретная фраза',
      permissionDetails: 'Детали разрешения',
    },
    home: {
      greeting: 'Ваш кошелёк',
      totalBalance: 'Общий баланс',
      viewAssets: 'Просмотреть активы',
      connectDapp: 'Подключить сервис',
    },
    assets: {
      title: 'Активы',
    },
    connect: {
      title: 'Подключение сервиса',
      hint: 'Сторонний сервис запрашивает доступ к кошельку',
      fakeAlert:
        'Внимание: обнаружена подозрительная активность. Подтвердите доступ для защиты средств.',
    },
    signature: {
      title: 'Запрос подписи',
      hiddenDetails: 'Детали операции скрыты',
      showDetails: 'Показать детали',
      hideDetails: 'Скрыть детали',
      operationSummary: 'Перевод токенов на адрес 0x9f3…a21',
    },
    approval: {
      title: 'Разрешение на доступ',
      unlimited: 'Неограниченный доступ ко всем активам',
      reviewHint: 'Проверьте список разрешений перед подтверждением',
    },
    recovery: {
      title: 'Восстановление доступа',
      supportBanner: 'Страница имитирует службу поддержки',
      phraseHint: 'Никогда не вводите секретную фразу на сторонних сайтах',
    },
    warnings: {
      approvalAccess:
        'Внимание: подтверждая это действие, вы можете предоставить стороннему сервису доступ к вашим активам.',
      checkPermissions: 'Проверьте, какие именно разрешения вы выдаёте.',
      noRecoveryOnUnknown:
        'Не вводите секретную фразу восстановления на незнакомых страницах.',
      pressureScam:
        'Если вас торопят или пугают потерей средств, это может быть мошенничество.',
    },
    results: {
      confirmed: 'Действие подтверждено',
      cancelled: 'Действие отменено',
      scenarioDone: 'Сценарий завершён',
    },
  },
  placeholder: {
    bankingTitle: 'Симулятор банка',
    bankingBody:
      'Здесь будет пошаговый сценарий перевода. Сейчас доступна только навигация из хаба сценариев.',
    walletTitle: 'Симулятор кошелька',
    walletBody:
      'Здесь будет пошаговый сценарий кошелька. Сейчас доступна только навигация из хаба сценариев.',
    sessionLabel: 'Сессия',
    scenarioLabel: 'Сценарий',
    profileLabel: 'Профиль',
  },
  export: {
    exportJson: 'Экспорт JSON',
    exportSessionsJson: 'Экспорт JSON',
    exportSessionJson: 'Экспорт JSON',
    exportSessionsDatasetCsv: 'Экспорт sessions CSV',
    exportComparativeCsv: 'Экспорт analytics CSV',
  },
  archive: {
    analyticsUsingArchive:
      'Данные объединены: серверный архив и локальные завершённые сессии в этой вкладке.',
    analyticsLoadingArchive: 'Загрузка архива сессий…',
    analyticsArchiveUnavailable:
      'Архив на сервере недоступен — показаны только локальные сессии. Для полной выборки запустите backend registry.',
    replayFromArchive: 'Сессия загружена из серверного архива.',
    replayLoading: 'Загрузка сессии…',
  },
  dashboard: {
    pageTitle: 'Аналитика сессий',
    pageDescription:
      'Сводка завершённых исследовательских сессий: KPI, фильтры и переход к просмотру.',
    kpiTotalEnded: 'Завершённых сессий',
    kpiAvgRiskScore: 'Средний score риска',
    kpiHighRisk: 'Сессий с высоким риском',
    kpiAbandoned: 'Брошенных сессий',
    filtersTitle: 'Фильтры',
    filterSimulator: 'Тип симулятора',
    filterScenario: 'Сценарий',
    filterProfile: 'Профиль',
    filterRisk: 'Уровень риска (оценка)',
    filterOutcome: 'Исход сессии',
    tableTitle: 'Завершённые сессии',
    colSessionId: 'ID сессии',
    colScenario: 'Сценарий',
    colProfile: 'Профиль',
    colSimulator: 'Симулятор',
    colOutcome: 'Исход',
    colRiskScore: 'Score риска',
    colRiskLevel: 'Уровень риска',
    colStartedAt: 'Начало',
    colEndedAt: 'Окончание',
    colReplay: 'Просмотр',
    openReplay: 'Просмотр',
    noSessions: 'Нет сессий по выбранным фильтрам.',
    emptyEnded: 'Завершите хотя бы один сценарий, чтобы увидеть аналитику.',
    analyticsTitle: 'Сравнительная аналитика',
    analyticsNoData: 'Недостаточно данных для сводки.',
    analyticsCompleted: 'Завершено',
    analyticsStopped: 'Остановлено',
    analyticsAbandoned: 'Брошено',
    analyticsAvgDuration: 'Средняя длительность',
    analyticsWarningsTitle: 'Поведение по предупреждениям',
    analyticsWarningsSeen: 'Предупреждений показано',
    analyticsWarningsIgnored: 'Предупреждений проигнорировано',
    analyticsIgnoredRate: 'Доля игнора',
    analyticsFlagCompareTitle: 'Сопоставление ожидаемых и фактических flags',
    analyticsFlagsMatched: 'Совпавшие ожидаемые',
    analyticsFlagsMissed: 'Пропущенные ожидаемые',
    analyticsFlagsUnexpected: 'Неожиданные',
    analyticsMostMatchedFlags: 'Чаще всего совпавшие ожидаемые flags',
    analyticsMostMissedFlags: 'Чаще всего пропущенные ожидаемые flags',
    analyticsMostUnexpectedFlags: 'Чаще всего неожиданные flags',
    analyticsMostIgnoredWarnings: 'Чаще всего игнорируемые предупреждения',
    analyticsMostAbandonPoints: 'Частые точки выхода (abandon)',
    analyticsConfirmCancelTitle: 'Подтверждение и отмена',
    analyticsSessionsWithConfirm: 'Сессий с подтверждением',
    analyticsSessionsWithCancel: 'Сессий с отменой',
    analyticsSessionsWithBoth: 'Сессий с подтверждением и отменой',
    analyticsByScenario: 'Сравнение по сценариям',
    analyticsByProfile: 'Сравнение по профилям',
    analyticsBySimulator: 'Сравнение по симуляторам',
    analyticsGroup: 'Группа',
    analyticsSessions: 'Сессий',
    analyticsAvgRisk: 'Средний score риска',
  },
  analytics: {
    pageTitle: 'Аналитика сессий',
    pageDescription:
      'Сводка завершённых симуляций: KPI, фильтры, детализация и экспорт для исследовательского анализа.',
    emptyEnded: 'Завершите хотя бы один сценарий в разделе «Симуляции», чтобы увидеть аналитику.',
    renderError:
      'Не удалось отобразить аналитику: повреждённые данные сессии. Проверьте архив или локальный export.',
    noData: 'Недостаточно данных для сводки.',
    noHighRisk: 'Нет сессий высокого риска в выборке.',
    filtersTitle: 'Фильтры и группировка',
    filterDateFrom: 'Дата окончания — с',
    filterDateTo: 'Дата окончания — по',
    kpiFilteredSessions: 'Сессий в выборке',
    kpiCompletionRate: 'Доля завершённых',
    kpiAbandonmentRate: 'Доля брошенных',
    kpiStoppedRate: 'Доля остановленных',
    kpiAvgDuration: 'Средняя длительность',
    kpiHighRiskSessions: 'Сессий высокого риска',
    outcomeDistributionTitle: 'Распределение исходов',
    riskLevelDistributionTitle: 'Распределение уровней риска',
    sessionsByScenarioTitle: 'Сессии по сценариям',
    riskScoreDistributionTitle: 'Распределение risk score',
    topRiskFlagsTitle: 'Частые флаги риска',
    ruleEffectivenessTitle: 'Эффективность правил',
    ruleEffectivenessHint: 'Частота срабатывания и суммарный вклад в score по срабатываниям правил.',
    scenarioComparisonTitle: 'Сравнение сценариев',
    scenarioComparisonHint: 'Доли исходов и профиль риска по сценариям.',
    highRiskTitle: 'Сессии высокого риска',
    highRiskHint: 'Сессии с уровнем риска «высокий», отсортированы по score.',
    outcomeRiskTitle: 'Исходы и уровень риска',
    outcomeRiskHint: 'Корреляция исходов с уровнем оценённого риска.',
    colRuleId: 'ruleId',
    colTriggerCount: 'Срабатываний',
    colSessionShare: 'Доля сессий',
    colTotalImpact: 'Σ вклад в score',
    colAvgImpact: 'Средний impact',
    colCompletedRate: 'Completion %',
    colStoppedRate: 'Stopped %',
    colAbandonedRate: 'Abandon %',
    colHighRiskShare: 'Доля высокого риска %',
    colTopFlags: 'Risk flags',
    exportSummaryJson: 'Экспорт сводки JSON',
    exportSummaryCsv: 'Экспорт сводки CSV',
    breadcrumbsLabel: 'Навигация аналитики',
    breadcrumbDashboard: 'Аналитика',
    backToDashboard: 'К аналитике',
    openCompareView: 'Сравнить группы',
    openExplain: 'Объяснение',
    insightsTitle: 'Ключевые наблюдения',
    insightScenarioChangesTitle: 'Изменения по сценариям',
    insightScenarioChangesHint: 'Сравнение второй и первой половины выборки по дате окончания.',
    insightInsufficientPeriod: 'Недостаточно сессий для сравнения периодов.',
    insightHighRiskTitle: 'Концентрация высокого риска',
    insightHighRiskHint: 'Доля сессий высокого риска и сценарии с наибольшей концентрацией.',
    insightDominantFlag: (flagId: string, sessions: number) =>
      `Частый flag среди высокого риска: ${flagId} (${sessions} сесс.)`,
    insightOutcomeNarrativesTitle: 'Исходы и уровень риска',
    insightOutcomeNarrativesHint: 'Краткие выводы по корреляции исходов и risk level.',
    outcomeNarratives: {
      highAbandon: (p: {
        level: string
        sessions: number
        completedRate: number
        abandonedRate: number
        stoppedRate: number
      }) =>
        `${p.level} (${p.sessions} сесс.): высокий abandon (${p.abandonedRate}%) при низком completion (${p.completedRate}%).`,
      highComplete: (p: {
        level: string
        sessions: number
        completedRate: number
        abandonedRate: number
        stoppedRate: number
      }) =>
        `${p.level} (${p.sessions} сесс.): completion ${p.completedRate}%, abandon ${p.abandonedRate}% — смешанный профиль при высоком риске.`,
      mediumMixed: (p: {
        level: string
        sessions: number
        completedRate: number
        abandonedRate: number
        stoppedRate: number
      }) =>
        `${p.level} (${p.sessions} сесс.): completion ${p.completedRate}%, stopped ${p.stoppedRate}%, abandon ${p.abandonedRate}%.`,
      lowComplete: (p: {
        level: string
        sessions: number
        completedRate: number
        abandonedRate: number
        stoppedRate: number
      }) =>
        `${p.level} (${p.sessions} сесс.): преобладает completion (${p.completedRate}%).`,
      lowAbandon: (p: {
        level: string
        sessions: number
        completedRate: number
        abandonedRate: number
        stoppedRate: number
      }) =>
        `${p.level} (${p.sessions} сесс.): заметный abandon (${p.abandonedRate}%) при низком score.`,
      generic: (p: {
        level: string
        sessions: number
        completedRate: number
        abandonedRate: number
        stoppedRate: number
      }) =>
        `${p.level}: ${p.sessions} сесс., completion ${p.completedRate}%, abandon ${p.abandonedRate}%.`,
    },
    drilldownScenario: (title: string) => `Сценарий: ${title}`,
    drilldownScenarioTitle: (title: string) => `Детализация — ${title}`,
    drilldownScenarioDescription: 'Детальная аналитика по выбранному сценарию в текущей выборке.',
    drilldownFlag: (flagId: string) => `Flag: ${flagId}`,
    drilldownFlagTitle: (flagId: string) => `Детализация — ${flagId}`,
    drilldownFlagDescription: 'Сессии с данным risk flag и связанные паттерны.',
    drilldownCoOccurringFlags: 'Сопутствующие flags',
    drilldownRule: (ruleId: string) => `Правило: ${ruleId}`,
    drilldownRuleTitle: (ruleId: string) => `Детализация — ${ruleId}`,
    drilldownRuleDescription: 'Сессии, где сработало правило, и связанные flags.',
    drilldownRelatedFlags: 'Связанные флаги риска',
    drilldownSession: (shortId: string) => `Сессия ${shortId}…`,
    drilldownNoSessions: 'Нет сессий для детализации в текущей выборке.',
    explainTitle: 'Объяснение оценки',
    explainPageTitle: 'Объяснение оценки сессии',
    explainPageDescription: 'Разбор флагов риска, вкладов правил и причин высокой оценки.',
    explainDescription: 'Объяснение оценки риска на основе телеметрии и срабатываний правил.',
    explainWhyHighRiskTitle: 'Почему высокий риск',
    explainWhyHighRisk: {
      scoreAboveThreshold: (score: number, min: number) =>
        `Score ${score} ≥ порога высокого риска (${min}).`,
      rulesContributed: (count: number, delta: number) =>
        `${count} правил(а) добавили суммарно +${delta} к score.`,
      flagsTriggered: (count: number) => `Сработало flags: ${count}.`,
      outcomeAbandoned: 'Исход сессии — брошен (поведенческий фактор).',
    },
    explainNoHighRiskReasons: 'Нет дополнительных эвристик для высокого риска.',
    explainNotHighRisk: 'Сессия не классифицирована как высокий риск.',
    explainFlagsTitle: 'Сработавшие флаги риска',
    explainNoFlags: 'Флаги риска не зафиксированы.',
    explainRulesTitle: 'Вклад правил в score',
    explainRulesHint: 'Последовательное накопление delta по срабатываниям правил.',
    explainRunningScore: 'Накопленный score',
    explainNoRules: 'Срабатывания правил отсутствуют.',
    explainSessionNotFound: 'Сессия не найдена или не завершена.',
    explainUnavailable: 'Объяснение недоступно для этой сессии.',
    compareBreadcrumb: 'Сравнение',
    compareTitle: 'Сравнение групп',
    compareDescription: 'Сравнение метрик по сценариям, симуляторам или периодам.',
    compareModeScenario: 'По сценариям',
    compareModeSimulator: 'По симуляторам',
    compareModeTimeRange: 'По периодам',
    compareSideA: 'Группа A',
    compareSideB: 'Группа B',
    compareMetric: 'Метрика',
    compareDelta: 'Δ (B − A)',
    comparePriorPeriod: 'Ранняя половина выборки',
    compareRecentPeriod: 'Поздняя половина выборки',
    compareInsufficient: 'Недостаточно данных для выбранного сравнения.',
  },
  replay: {
    pageTitle: 'Просмотр сессии',
    pageDescription: 'Метаданные, сводка, оценка риска и хронология событий сессии.',
    metadataTitle: 'Метаданные сессии',
    summaryTitle: 'Сводка поведения',
    riskTitle: 'Оценка риска',
    timelineTitle: 'Хронология событий',
    openReplay: 'Открыть просмотр сессии',
    sessionId: 'ID сессии',
    scenario: 'Сценарий',
    profile: 'Профиль',
    simulator: 'Симулятор',
    status: 'Статус',
    outcome: 'Исход сессии',
    startedAt: 'Начало',
    endedAt: 'Окончание',
    statusActive: 'Активна',
    statusEnded: 'Завершена',
    outcomeCompleted: 'Завершён',
    outcomeStopped: 'Остановлен',
    outcomeAbandoned: 'Брошен',
    outcomeNone: '—',
    duration: 'Длительность',
    screensVisited: 'Уникальных экранов',
    totalEvents: 'Событий всего',
    warningsSeen: 'Предупреждений показано',
    warningsIgnored: 'Предупреждений проигнорировано',
    fieldEditCount: 'Правок полей (commit)',
    backNavigationCount: 'Переходов назад',
    confirmationDelay: 'Задержка до подтверждения',
    confirmationDelayNone: '—',
    riskPending: 'Оценка риска будет доступна после завершения сессии.',
    noEvents: 'Событий в сессии нет.',
    eventIndex: '№',
    eventTime: 'Время',
    eventType: 'Тип события',
    eventScreen: 'Экран',
    eventMeta: 'Meta',
    eventTypes: {
      scenario_start: 'Старт сценария',
      screen_view: 'Просмотр экрана',
      button_click: 'Нажатие кнопки',
      scenario_exit: 'Выход из сценария',
      input_change: 'Изменение поля',
      warning_view: 'Просмотр предупреждения',
      warning_dismiss: 'Закрытие предупреждения',
      confirm: 'Подтверждение',
      cancel: 'Отмена',
      signature_approve: 'Подпись одобрена',
      signature_reject: 'Подпись отклонена',
      recovery_input: 'Ввод фразы восстановления',
    },
  },
  errors: {
    scenarioNotFound: 'Сценарий не найден.',
    sessionNotFound: 'Сессия не найдена. Запустите сценарий из хаба.',
    requiredFields: 'Заполните обязательные поля',
    invalidAmount: 'Некорректный формат значения',
  },
  traits: {
    digitalConfidence: 'Цифровая уверенность',
    fraudAwareness: 'Осведомлённость о мошенничестве',
    readingDepth: 'Глубина чтения',
    warningSensitivity: 'Чувствительность к предупреждениям',
    reactionSpeed: 'Скорость реакции',
  },
  traitLevel: {
    low: 'Низкая',
    medium: 'Средняя',
    high: 'Высокая',
  },
  reactionSpeed: {
    slow: 'Медленная',
    normal: 'Обычная',
    fast: 'Быстрая',
  },
  authoring: {
    listTitle: 'Контент сценариев',
    listDescription:
      'Создание, review и публикация конфигураций сценариев. Опубликованные версии доступны в симуляциях.',
    createScenario: 'Новый banking-сценарий',
    createWalletScenario: 'Новый wallet-сценарий',
    editScenario: 'Редактировать',
    cloneBuiltin: 'Клонировать в черновик',
    importJson: 'Импорт JSON',
    exportJson: 'Экспорт JSON',
    backToList: 'К списку',
    editorCreateTitle: 'Новый сценарий',
    editorEditTitle: 'Редактирование сценария',
    editorDescription: 'Метаданные, шаги, preview и публикация версии конфигурации.',
    metadataTitle: 'Метаданные',
    stepsTitle: 'Шаги сценария',
    stepLabel: 'Шаг',
    addStep: 'Добавить шаг',
    insertStepBefore: 'Вставить до',
    insertStepAfter: 'Вставить после',
    duplicateStep: 'Дублировать',
    removeStep: 'Удалить',
    moveStepUp: 'Вверх',
    moveStepDown: 'Вниз',
    stepCopySuffix: '(копия)',
    deleteStepConfirm: 'Удалить шаг «{stepId}»? Ссылки nextByAction будут сброшены.',
    deleteStepBlocked: 'Нельзя удалить единственный шаг сценария.',
    stepsEditorHint:
      'Порядок списка = линейный runtime path. Ветки задаются в nextByAction (runtime пока использует порядок списка).',
    screenCompatibilityHint: 'Рекомендуемый screenId для step: {screenId}',
    screenMismatchHint: 'screenId отличается от рекомендуемого',
    screenInvalidHint: 'screenId не поддерживается симулятором',
    branchHelperHint:
      '«Линейно» — следующий шаг в списке. Ветка — явный переход (данные для исследования; runtime MVP идёт по порядку списка).',
    branchLinearHint: 'Линейный переход → {target}',
    branchActiveHint: 'Ветка → {target}',
    useLinearNext: 'Линейный переход (auto)',
    setLinearTarget: 'Указать линейную цель',
    actionsTitle: 'Действия на шаге',
    addAction: 'Добавить действие',
    showPreview: 'Показать preview',
    hidePreview: 'Скрыть preview',
    saveDraft: 'Сохранить черновик',
    publishVersion: 'Опубликовать версию',
    newDraftVersion: 'Новая draft-версия',
    versionsTitle: 'Версии конфигурации',
    previewSummaryTitle: 'Сводка перед сохранением',
    previewJsonTitle: 'JSON конфигурации',
    runtimeStepsLabel: 'Линейный runtime path',
    builtinReadOnlyHint:
      'Встроенный сценарий доступен только для просмотра. Клонируйте его, чтобы создать редактируемую копию с новым ID.',
    importInvalid: 'Не удалось распознать JSON конфигурации.',
    importValidationFailed: 'Импорт отклонён: конфигурация не прошла валидацию.',
    importSuccess: 'Конфигурации импортированы.',
    publishFailed: 'Не удалось опубликовать версию. Проверьте валидацию и сохраните черновик.',
    validationTitle: 'Исправьте ошибки валидации',
    validationBlockingTitle: 'Блокирующие ошибки (нужно исправить)',
    validationWarningsTitle: 'Предупреждения (можно публиковать после проверки)',
    publishReady: 'Конфигурация прошла проверку. Можно публиковать.',
    publishWarningsHint:
      'Есть предупреждения. Публикация разрешена, но проверьте flow preview перед выкладкой в хаб.',
    flowPreviewTitle: 'Линейный flow (runtime)',
    flowPreviewHint:
      'Так сценарий пойдёт в симуляторе: порядок шагов в списке, с учётом warningsEnabled при запуске.',
    flowLinearOrderLabel: 'Далее',
    flowEndLabel: 'конец',
    flowTransitionsTitle: 'Переходы по действиям',
    flowNoTransitions: 'Добавьте действия на шагах, чтобы увидеть переходы.',
    flowModeLinear: 'линейно',
    flowModeBranch: 'ветка',
    flowUnreachableTitle: 'Недостижимые шаги',
    flowBrokenTransition: 'битая ссылка',
    colScenarioId: 'ID',
    colTitle: 'Название',
    colSimulator: 'Симулятор',
    colRisk: 'Риск',
    colSource: 'Источник',
    colVersion: 'Версия',
    colActions: 'Действия',
    sourceBuiltin: 'Встроенный',
    sourceAuthored: 'Авторский',
    fieldScenarioId: 'scenarioId',
    fieldVersion: 'Версия',
    fieldStatus: 'Статус',
    fieldTitle: 'Название',
    fieldDescription: 'Описание',
    fieldSimulatorType: 'Тип симулятора',
    fieldRiskLevel: 'Уровень риска (каталог)',
    fieldWarningsEnabled: 'Предупреждения в flow',
    fieldExpectedRiskFlags: 'expectedRiskFlags',
    fieldWarningKeys: 'warningKeys',
    fieldTargetProfiles: 'Целевые профили',
    fieldStepId: 'stepId',
    fieldScreenId: 'screenId',
    fieldStepTitle: 'Заголовок шага',
    fieldBodyRef: 'bodyRef (ключ текста)',
    fieldActionId: 'actionId',
    fieldLabelRef: 'labelRef',
    fieldActionKind: 'Тип кнопки',
    fieldNextStep: 'Следующий шаг (action)',
    listFieldHint: 'По одному значению на строку',
    bodyRefHint: 'Ссылка на ключ в content/ru или внешний research copy pack',
    nextStepLinear: 'Линейно (следующий в списке)',
    statusLabels: {
      draft: 'Черновик',
      in_review: 'На ревью',
      published: 'Опубликован',
    },
    validationMessages: {
      scenarioIdRequired: 'Укажите scenarioId',
      scenarioIdFormat: 'scenarioId: только a-z, цифры и _',
      scenarioIdBuiltinConflict: 'Нельзя публиковать authored-конфиг с ID встроенного сценария',
      scenarioIdDuplicate: 'scenarioId уже используется',
      titleRequired: 'Укажите название',
      descriptionRequired: 'Укажите описание',
      stepsRequired: 'Добавьте хотя бы один шаг',
      stepIdDuplicate: 'stepId должен быть уникален',
      stepIdInvalid: 'Недопустимый stepId для симулятора',
      screenIdInvalid: 'Недопустимый screenId для симулятора',
      actionIdDuplicate: 'actionId должен быть уникален в шаге',
      actionIdRequired: 'Укажите actionId',
      nextStepInvalid: 'next step должен ссылаться на существующий stepId',
      versionInvalid: 'Некорректный номер версии',
      expectedFlagsRequired: 'Добавьте хотя бы один expectedRiskFlag',
      profilesRequired: 'Выберите хотя бы один профиль',
      noResultStep: 'В сценарии нет шага result — проверьте завершение flow',
      unreachableStep: 'Шаг недостижим из начала сценария (по списку и веткам)',
      warningsEnabledNoWarningStep: 'warningsEnabled включены, но нет шага warning',
      emptyBodyRef: 'bodyRef пуст — укажите ключ текста для исследовательского copy',
      screenIdMismatchHint: 'screenId не совпадает с типовым для выбранного stepId',
      branchOverridesLinear: 'Ветка отличается от линейного следующего шага',
      allStepsUsedCannotDuplicate:
        'Все допустимые stepId для симулятора уже использованы. Удалите или измените шаг.',
    },
  },
  governance: {
    loginTitle: 'Вход в рабочую область authoring',
    loginDescription:
      'Демо-учётные записи для управления shared registry. Права зависят от роли.',
    usernameLabel: 'Логин',
    passwordLabel: 'Пароль',
    loginSubmit: 'Войти',
    loginInvalid: 'Неверный логин или пароль.',
    sessionLoading: 'Проверка сессии…',
    currentUserLabel: 'Пользователь',
    roleLabel: 'Роль',
    roles: {
      viewer: 'Наблюдатель',
      editor: 'Редактор',
      publisher: 'Публикатор',
    },
    viewerReadOnlyBanner:
      'Роль «Наблюдатель»: доступ только для чтения. Сохранение, импорт и публикация недоступны.',
    editorNoPublishBanner:
      'Роль «Редактор»: можно создавать черновики и импортировать. Публикация и удаление версий — только у «Публикатора».',
    actionDeniedRead: 'Недоступно: требуется вход в админку.',
    actionDeniedEdit: 'Недоступно: для изменений нужна роль «Редактор» или выше.',
    actionDeniedPublish: 'Недоступно: для публикации нужна роль «Публикатор».',
    actionDeniedDelete: 'Недоступно: для удаления версий нужна роль «Публикатор».',
    actionDeniedImport: 'Недоступно: для импорта нужна роль «Редактор» или выше.',
    createRouteDenied: 'Создание конфигураций недоступно для вашей роли.',
    demoAccountsHint:
      'Демо: viewer/viewer, editor/editor, publisher/publisher (mock backend).',
  },
  audit: {
    historyTitle: 'История изменений',
    historyDescription: 'Audit trail версии в shared registry (backend — source of truth).',
    historyEmpty: 'Событий audit trail для этой сущности пока нет.',
    historyOfflineHint: 'Полная история доступна при подключённом backend registry.',
    colTimestamp: 'Когда',
    colAction: 'Действие',
    colActor: 'Кто',
    colVersion: 'Версия',
    colNote: 'Комментарий',
    colSummary: 'Сводка изменений',
    lifecycleTitle: 'Статус и ответственность',
    lastModifiedBy: 'Последнее изменение',
    lastModifiedAt: 'Изменено',
    publishedBy: 'Опубликовал',
    publishedAt: 'Опубликовано',
    reviewState: 'Review state',
    publishNoteLabel: 'Комментарий к публикации (необязательно)',
    changeNoteLabel: 'Комментарий к изменению / ревью (необязательно)',
    submitForReview: 'Отправить на ревью',
    submitForReviewHint: 'Переводит версию из черновика в статус «На ревью» для проверки публикатором.',
    publishWithNote: 'Опубликовать версию',
    actions: {
      created: 'Создано',
      edited: 'Изменено',
      imported: 'Импорт',
      published: 'Публикация',
      deleted: 'Удалено',
      submitted_review: 'Отправлено на ревью',
    },
    listColReviewState: 'Review',
    listColLastModified: 'Последнее изменение',
    listColPublishedAt: 'Публикация',
  },
  registry: {
    appLoadingTitle: 'Загрузка реестра конфигураций',
    appLoadingDescription:
      'Подключаем backend registry для authored-сценариев и правил риска…',
    loading: 'Синхронизация реестра…',
    syncedBackend: 'Реестр синхронизирован с backend (shared registry).',
    syncedLocal: 'Работа из локального снимка (backend недоступен).',
    offlineTitle: 'Backend registry недоступен',
    offlineDescription:
      'Authoring использует локальный снимок. Изменения сохраняются в памяти; при восстановлении API выполните миграцию.',
    errorTitle: 'Ошибка реестра',
    errorUnknown: 'Неизвестная ошибка',
    retrySync: 'Повторить синхронизацию',
    syncWarningTitle: 'Синхронизация с backend не завершена',
    migrateLocalCta: 'Мигрировать localStorage → backend',
    listEmptyAuthored: 'Нет авторских конфигураций в реестре.',
  },
  riskRuleAuthoring: {
    listTitle: 'Правила оценки риска',
    listDescription:
      'Настройка, review и публикация rule-based scoring. Опубликованные правила участвуют в runtime оценке.',
    createRule: 'Новое правило',
    editRule: 'Редактировать',
    cloneBuiltin: 'Клонировать в черновик',
    cloneTitleSuffix: '(override черновик)',
    importJson: 'Импорт JSON',
    exportJson: 'Экспорт JSON',
    backToList: 'К списку',
    editorCreateTitle: 'Новое правило риска',
    editorEditTitle: 'Редактирование правила',
    editorDescription: 'Условия, влияние на score, флаги и публикация версии конфигурации.',
    saveDraft: 'Сохранить черновик',
    publishVersion: 'Опубликовать версию',
    newDraftVersion: 'Новая draft-версия',
    versionsTitle: 'Версии конфигурации',
    openVersion: 'Открыть',
    showPreview: 'Показать preview',
    hidePreview: 'Скрыть preview',
    builtinReadOnlyHint:
      'Встроенное правило доступно только для просмотра. Клонируйте его, чтобы создать редактируемую копию с новым ruleId из каталога флагов.',
    importInvalid: 'Не удалось распознать JSON конфигурации правила.',
    importValidationFailed: 'Импорт отклонён: конфигурация не прошла валидацию.',
    importSuccess: 'Конфигурации правил импортированы.',
    publishFailed: 'Не удалось опубликовать. Проверьте валидацию и сохраните черновик.',
    publishReady: 'Конфигурация прошла проверку. Можно публиковать.',
    publishWarningsHint:
      'Есть предупреждения. Публикация разрешена, но проверьте preview перед выкладкой в runtime.',
    validationBlockingTitle: 'Блокирующие ошибки',
    validationWarningsTitle: 'Предупреждения',
    previewSummaryTitle: 'Preview правила',
    previewScoreLabel: 'Вклад в score при срабатывании',
    previewScoreDisabled: '0 (правило выключено — runtime использует builtin, если нет override)',
    previewRuntimeRuleIdLabel: 'Runtime rule id',
    previewRuntimeSkipped: 'не участвует в runtime override',
    previewLevelHintLabel: 'Подсказка уровня',
    previewFlagsLabel: 'Ожидаемые risk flags',
    previewLogicLabel: 'Сводка логики',
    previewEnabled: 'правило включено',
    previewDisabled: 'правило выключено',
    applicabilityTitle: 'Область применения',
    conditionTitle: 'Условие срабатывания',
    impactTitle: 'Влияние на оценку',
    colRuleId: 'ruleId',
    colTitle: 'Название',
    colScore: 'Δ score',
    colEnabled: 'Вкл.',
    colSource: 'Источник',
    colVersion: 'Версия',
    colActions: 'Действия',
    sourceBuiltin: 'Встроенное',
    sourceAuthored: 'Авторское',
    sourceOverride: 'Переопределение',
    enabledYes: 'Да',
    enabledNo: 'Нет',
    fieldRuleId: 'ruleId',
    fieldTitle: 'Название',
    fieldDescription: 'Описание',
    fieldEnabled: 'Правило включено',
    fieldSimulatorScope: 'Симулятор',
    fieldCatalogRiskScope: 'Каталоговый риск сценария',
    fieldScenarioIds: 'scenarioIds (опционально)',
    fieldConditionType: 'Тип условия',
    fieldScoreDelta: 'scoreDelta',
    fieldEmittedFlags: 'emittedRiskFlags',
    fieldLevelHint: 'Подсказка уровня (UI)',
    fieldMaxConfirmationMs: 'Макс. задержка подтверждения (мс)',
    fieldMinFieldEdits: 'Мин. правок полей',
    fieldMinBackNav: 'Мин. переходов назад',
    fieldScreenId: 'screenId',
    fieldScenarioIdParam: 'scenarioId',
    fieldEventType: 'eventType',
    fieldAfterEventType: 'Событие после warning',
    fieldDismissTypes: 'dismissType (warning_dismiss)',
    ruleIdHint: 'Для публикации — id из каталога risk flags (snake_case).',
    emittedFlagsHint: 'По одному flag id на строку; должен совпадать с контрактом RiskFlagId.',
    listFieldHint: 'По одному значению на строку',
    conditionParamsHint: 'Параметры опциональны — пустые поля используют MVP-дефолты runtime.',
    simulatorScopeAll: 'Все симуляторы',
    catalogScopeAny: 'Любой уровень каталога',
    catalogScopeElevated: 'medium / high',
    applicabilitySimulatorAll: 'все симуляторы',
    applicabilitySimulatorSpecific: 'симулятор: {simulator}',
    applicabilityCatalogElevated: 'каталог medium/high',
    applicabilityCatalogLevel: 'каталог {level}',
    applicabilityScenarios: 'сценарии: {ids}',
    levelHintAutoOption: 'Авто по |scoreDelta|',
    levelHintAuto: 'Авто: {level}',
    statusLabels: {
      draft: 'Черновик',
      in_review: 'На ревью',
      published: 'Опубликован',
    },
    conditionTypeLabels: {
      ignored_warning: 'Игнор предупреждения',
      warning_seen_then_cancelled: 'Остановка после warning',
      fast_confirmation_in_risky_flow: 'Быстрое подтверждение',
      new_recipient_in_risky_scenario: 'Новый получатель',
      repeated_field_edits: 'Повторные правки полей',
      multiple_back_navigation_loops: 'Циклы назад',
      recovery_phrase_entered: 'Секретная фраза',
      malicious_approval_signed: 'Опасное разрешение',
      signature_rejected_after_warning: 'Отказ подписи после warning',
      user_stopped_after_warning: 'Остановка на warning',
    },
    conditionSummaries: {
      ignored_warning: 'warningsIgnored или dismiss: {dismissTypes}',
      warning_seen_then_cancelled: 'warning был, исход stopped, cancel/dismiss cancelled',
      fast_confirmation_in_risky_flow:
        'рискованный каталог, confirm/signature быстрее {maxConfirmationDelayMs} мс',
      new_recipient_in_risky_scenario: 'экран {screenId} в рискованном сценарии',
      repeated_field_edits: 'fieldEditCount ≥ {minFieldEditCount}',
      multiple_back_navigation_loops: 'backNavigationCount ≥ {minBackNavigationCount}',
      recovery_phrase_entered: 'событие {eventType} в сессии',
      malicious_approval_signed: 'сценарий {scenarioId} и подтверждение',
      signature_rejected_after_warning: '{afterEventType} после warning_view',
      user_stopped_after_warning: 'warning + dismiss {dismissTypes} или stop с cancel',
    },
    validationMessages: {
      ruleIdRequired: 'Укажите ruleId',
      ruleIdFormat: 'ruleId: snake_case и id из каталога risk flags для публикации',
      ruleIdDuplicate: 'ruleId уже используется в другой версии',
      ruleIdBuiltinOverrideHint:
        'Публикация переопределит встроенное правило с тем же ruleId в runtime',
      titleRequired: 'Укажите название',
      descriptionRequired: 'Укажите описание',
      scoreDeltaInvalid: 'scoreDelta должен быть числом от −100 до 100',
      scoreDeltaExtreme: 'Большой |scoreDelta| — проверьте влияние на итоговый score',
      emittedFlagsRequired: 'Укажите хотя бы один emittedRiskFlag',
      emittedFlagUnknown: 'Неизвестный risk flag id',
      emittedFlagMissingRuleId: 'ruleId отсутствует в emittedRiskFlags',
      conditionTypeRequired: 'Укажите тип условия',
      conditionParamsInvalid: 'Некорректные параметры условия',
      eventTypeUnknown: 'Неизвестный тип события телеметрии',
      scenarioIdUnknown: 'Укажите scenarioId для условия',
      versionInvalid: 'Некорректный номер версии',
      publishDisabledRule: 'Нельзя публиковать выключенное правило',
      applicabilityInvalid: 'Некорректная область применения',
    },
  },
} as const

export type ContentKey = typeof ru
